/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Users } from '../RestModels';
/**
 * TODOApi - axios parameter creator
 * @export
 */
export const TODOApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} right The Right to check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser: async (right: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'right' is not null or undefined
            assertParamExists('deleteUser', 'right', right)
            const localVarPath = `/chaos/api/users/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (right !== undefined) {
                localVarQueryParameter['right'] = right;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TODOApi - functional programming interface
 * @export
 */
export const TODOApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TODOApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} right The Right to check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUser(right: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Users>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(right, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TODOApi.deleteUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TODOApi - factory interface
 * @export
 */
export const TODOApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TODOApiFp(configuration)
    return {
        /**
         * 
         * @param {TODOApiDeleteUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(requestParameters: TODOApiDeleteUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<Users> {
            return localVarFp.deleteUser(requestParameters.right, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteUser operation in TODOApi.
 * @export
 * @interface TODOApiDeleteUserRequest
 */
export interface TODOApiDeleteUserRequest {
    /**
     * The Right to check
     * @type {string}
     * @memberof TODOApiDeleteUser
     */
    readonly right: string
}

/**
 * TODOApi - object-oriented interface
 * @export
 * @class TODOApi
 * @extends {BaseAPI}
 */
export class TODOApi extends BaseAPI {
    /**
     * 
     * @param {TODOApiDeleteUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TODOApi
     */
    public deleteUser(requestParameters: TODOApiDeleteUserRequest, options?: RawAxiosRequestConfig) {
        return TODOApiFp(this.configuration).deleteUser(requestParameters.right, options).then((request) => request(this.axios, this.basePath));
    }
}

