/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Channels = {
    amabc: 'AMABC',
    acc: 'ACC',
    acc_network_extra: 'ACCNetworkExtra',
    espn: 'ESPN',
    espn2: 'ESPN2',
    espnu: 'ESPNU',
    esp_news: 'ESPNews',
    espn3: 'ESPN3',
    espn_deportes: 'ESPNDeportes',
    sec_network: 'SECNetwork',
    sec_network_plus: 'SECNetworkPlus',
    espn_plus: 'ESPNPlus',
    espn_classic: 'EspnClassic',
    longhorn: 'LONGHORN'
} as const;

export type Channels = typeof Channels[keyof typeof Channels];



