/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Filters
 */
export interface Filters {
    /**
     * 
     * @type {Array<boolean>}
     * @memberof Filters
     */
    'enabled'?: Array<boolean> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Filters
     */
    'gender'?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof Filters
     */
    'pagination_current'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Filters
     */
    'pagination_page_size'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Filters
     */
    'sort_field'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Filters
     */
    'sort_order'?: string | null;
}

