/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PartialUser
 */
export interface PartialUser {
    /**
     * 
     * @type {string}
     * @memberof PartialUser
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof PartialUser
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof PartialUser
     */
    'username': string;
}

