/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Filters } from './filters';
// May contain unused imports in some cases
// @ts-ignore
import type { Users } from './users';

/**
 * 
 * @export
 * @interface Response
 */
export interface Response {
    /**
     * 
     * @type {Array<Users>}
     * @memberof Response
     */
    'data': Array<Users>;
    /**
     * 
     * @type {Filters}
     * @memberof Response
     */
    'filters': Filters;
    /**
     * 
     * @type {number}
     * @memberof Response
     */
    'total': number;
}

