/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Right = {
    admin: 'Admin',
    users: 'Users',
    posts: 'Posts',
    comments: 'Comments',
    user_management: 'UserManagement',
    right_management: 'RightManagement',
    migration_management: 'MigrationManagement',
    channel_data_management: 'ChannelDataManagement'
} as const;

export type Right = typeof Right[keyof typeof Right];



