/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Users
 */
export interface Users {
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'email': string;
    /**
     * 
     * @type {boolean}
     * @memberof Users
     */
    'enabled': boolean;
    /**
     * 
     * @type {number}
     * @memberof Users
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'location': string;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'username': string;
    /**
     * 
     * @type {boolean}
     * @memberof Users
     */
    'validated': boolean;
}

