// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct Data {
    pub id: i32,
    pub title: String,
    pub description: String,
    pub channel: String,
    pub start: NaiveDateTime,
    pub end: NaiveDateTime,
    pub sport_id: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Job {
    pub id: i32,
    pub title: String,
    pub description: String,
    pub created_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
    pub deleted: Option<bool>,
}

#[derive(Queryable, Debug)]
pub struct PasswordReset {
    pub id: i32,
    pub email: String,
    pub token: String,
    pub created_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Sport {
    pub id: i32,
    pub name: String,
    pub regex: String,
}

#[derive(Queryable, Debug)]
pub struct TestTable {
    pub id: u64,
    pub name: String,
}

#[derive(Queryable, Debug)]
pub struct UserRight {
    pub id: i32,
    pub user_id: i32,
    pub right_name: String,
    pub created_at: NaiveDateTime,
    pub created_by: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct UserRightsHistory {
    pub id: i32,
    pub user_id: i32,
    pub right_name: String,
    pub created_at: NaiveDateTime,
    pub created_by: Option<i32>,
    pub deleted_at: Option<NaiveDateTime>,
    pub deleted_by: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub email: String,
    pub password: String,
    pub location: String,
    pub created_at: NaiveDateTime,
    pub enabled: bool,
    pub validated: bool,
    pub validation_key: Option<String>,
}

