CREATE TABLE IF NOT EXISTS transaction_data (
	id BIGSERIAL PRIMARY KEY,
	statement_id INTEGER NOT NULL,
	category_id INTEGER,
	description TEXT NOT NULL,
	amount INTEGER NOT NULL,
	transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status VARCHAR(50) NOT NULL
);
