-- Funds Manager — PostgreSQL schema (ported from MySQL migrations)
-- Apply before data import: psql $POSTGRES_URL -f database/sql/postgres/schema.sql

CREATE TYPE category_mappings_match_type AS ENUM ('exact', 'regex');

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    parent_category_id BIGINT REFERENCES categories (id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    colour VARCHAR(7)
);

CREATE TABLE category_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    match_type category_mappings_match_type NOT NULL DEFAULT 'exact',
    category_id BIGINT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    priority INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_category_mappings_pattern ON category_mappings (pattern);
CREATE INDEX idx_category_mappings_priority ON category_mappings (priority);

CREATE TABLE statement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    account_id VARCHAR(25) NOT NULL,
    opening_balance INTEGER NOT NULL DEFAULT 0,
    closing_balance INTEGER NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transaction_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id INTEGER NOT NULL,
    category_id INTEGER,
    description TEXT NOT NULL,
    amount INTEGER NOT NULL,
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    balance INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_transaction_data_statement_id ON transaction_data (statement_id);
CREATE INDEX idx_transaction_data_transaction_date ON transaction_data (transaction_date);
CREATE INDEX idx_transaction_data_category_id ON transaction_data (category_id);
CREATE INDEX idx_transaction_data_active_date_id ON transaction_data (transaction_date DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_transaction_data_active_spending ON transaction_data (category_id, transaction_date DESC) WHERE deleted_at IS NULL AND amount < 0;
CREATE INDEX idx_statement_active_date_id ON statement (date DESC, id DESC) WHERE deleted_at IS NULL;

CREATE TABLE transaction_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES transaction_data (id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (transaction_id, category_id)
);

CREATE TABLE __diesel_schema_migrations (
    version VARCHAR(50) PRIMARY KEY,
    run_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
