use actix_web::{HttpResponse, Responder};
use serde::Serialize;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct QueryParamDoc {
    name: &'static str,
    #[serde(rename = "type")]
    param_type: &'static str,
    required: bool,
    description: &'static str,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct EndpointDoc {
    method: &'static str,
    path: &'static str,
    query: Vec<QueryParamDoc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    body: Option<&'static str>,
    response: &'static str,
    purpose: &'static str,
    #[serde(rename = "aiUse")]
    ai_use: &'static str,
    #[serde(rename = "readOnly")]
    read_only: bool,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct EndpointGroup {
    id: &'static str,
    label: &'static str,
    description: &'static str,
    endpoints: Vec<EndpointDoc>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct RecommendedRead {
    label: &'static str,
    path: &'static str,
    why: &'static str,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ApiCatalog {
    catalog_url: &'static str,
    mcp_url: &'static str,
    openapi_url: &'static str,
    version_url: &'static str,
    base_path: &'static str,
    transport: TransportDoc,
    conventions: Vec<&'static str>,
    recommended_reads: Vec<RecommendedRead>,
    groups: Vec<EndpointGroup>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct TransportDoc {
    dev_protocol: &'static str,
    default_port: u16,
    auth: &'static str,
    date_format: &'static str,
    amounts: &'static str,
}

fn date_range_params(required: bool) -> Vec<QueryParamDoc> {
    vec![
        QueryParamDoc {
            name: "start",
            param_type: "date",
            required,
            description: "Range start (YYYY-MM-DD). Omit with end for all-time analytics.",
        },
        QueryParamDoc {
            name: "end",
            param_type: "date",
            required,
            description: "Range end (YYYY-MM-DD), inclusive.",
        },
        QueryParamDoc {
            name: "account_id",
            param_type: "integer",
            required: false,
            description: "Limit to one financial account.",
        },
    ]
}

fn catalog() -> ApiCatalog {
    ApiCatalog {
        catalog_url: "/api/ai",
        mcp_url: "/api/mcp",
        openapi_url: "/api/openapi.json",
        version_url: "/api/version",
        base_path: "/api",
        transport: TransportDoc {
            dev_protocol: "https",
            default_port: 2020,
            auth: "none (local/trusted network only)",
            date_format: "YYYY-MM-DD",
            amounts: "dollars in JSON responses unless field name ends with _cents",
        },
        conventions: vec![
            "All JSON routes live under /api.",
            "Confirmed inter-account transfers are excluded from spending/income analytics, not from transaction lists or balances.",
            "Use group_by_parent=true on dashboard and drilldowns to roll up child categories.",
            "Paginated lists return { items, total, page, per_page, total_pages }.",
            "POST/PATCH/PUT bodies are application/json unless uploading statements (multipart/form-data).",
        ],
        recommended_reads: vec![
            RecommendedRead {
                label: "Period snapshot",
                path: "/api/analytics/kpis?start=2025-01-01&end=2025-06-30",
                why: "Headline spending, income, net, and latest balance for a date range.",
            },
            RecommendedRead {
                label: "Trends and category mix",
                path: "/api/analytics/dashboard?start=2025-01-01&end=2025-06-30&group_by_parent=true",
                why: "Monthly cashflow, category pies, and daily balance history.",
            },
            RecommendedRead {
                label: "Recurring patterns",
                path: "/api/analytics/recurring?min_occurrences=3",
                why: "Subscriptions, salary, and other repeating credits/debits.",
            },
            RecommendedRead {
                label: "Income sources",
                path: "/api/income-streams",
                why: "Detected salary and other regular income with user labels.",
            },
            RecommendedRead {
                label: "Category drill-down",
                path: "/api/analytics/breakdown?start=2025-01-01&end=2025-06-30",
                why: "Parent categories with sub-merchant rows before pulling transactions.",
            },
            RecommendedRead {
                label: "Accounts context",
                path: "/api/accounts?with_stats=true",
                why: "Account names, parsers, and last known balances.",
            },
        ],
        groups: vec![
            EndpointGroup {
                id: "discovery",
                label: "Discovery",
                description: "Start here. This catalog and API metadata.",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/ai",
                        query: vec![],
                        body: None,
                        response: "This document (JSON catalog of all endpoints).",
                        purpose: "Machine-readable API guide for AI agents and MCP tools.",
                        ai_use: "Fetch once at session start to learn available data and suggested read order.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/mcp",
                        query: vec![],
                        body: None,
                        response: "Same JSON as /api/ai.",
                        purpose: "Alias for MCP-oriented clients.",
                        ai_use: "Use interchangeably with /api/ai.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/openapi.json",
                        query: vec![],
                        body: None,
                        response: "OpenAPI 3 document (schemas not yet annotated).",
                        purpose: "Future machine schema; prefer /api/ai for now.",
                        ai_use: "Check version info only until utoipa paths are added.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/version",
                        query: vec![],
                        body: None,
                        response: "{ version, gitSha }",
                        purpose: "Deployed app version.",
                        ai_use: "Confirm which build you are talking to.",
                        read_only: true,
                    },
                ],
            },
            EndpointGroup {
                id: "analytics",
                label: "Analytics",
                description: "Aggregated spending, income, balances, and patterns. Best source for financial analysis.",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/kpis",
                        query: date_range_params(false),
                        body: None,
                        response: "{ spending, income, net, balance } in dollars.",
                        purpose: "Headline totals for a period.",
                        ai_use: "Answer 'how much did I spend/earn' and net cashflow questions.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/dashboard",
                        query: {
                            let mut q = date_range_params(false);
                            q.push(QueryParamDoc {
                                name: "group_by_parent",
                                param_type: "boolean",
                                required: false,
                                description: "Roll child categories into parents for pies.",
                            });
                            q
                        },
                        body: None,
                        response: "monthlySummary, spendingByCategory, incomeByCategory, balanceSeries, balanceStack.",
                        purpose: "Charts data: monthly trends, category breakdown, daily balances.",
                        ai_use: "Explain trends, category mix, and balance trajectory over time.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/net-worth",
                        query: date_range_params(false),
                        body: None,
                        response: "[{ date, availableCash, assets, liabilities, netWorth }].",
                        purpose: "Net worth time series including manual assets/liabilities.",
                        ai_use: "Wealth trajectory and balance-sheet questions.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/breakdown",
                        query: date_range_params(true),
                        body: None,
                        response: "Parent categories with nested subRows (merchant groups).",
                        purpose: "Hierarchical spend/income by category before transaction detail.",
                        ai_use: "Find which categories or merchants drove changes.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/recurring",
                        query: vec![
                            QueryParamDoc {
                                name: "min_occurrences",
                                param_type: "integer",
                                required: false,
                                description: "Minimum matching transactions (default 3).",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Limit to one account.",
                            },
                        ],
                        body: None,
                        response: "Recurring expense and income candidates with cadence and amounts.",
                        purpose: "Detect subscriptions, bills, and salary patterns.",
                        ai_use: "Flag recurring costs, estimate monthly burn, compare to income streams.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/spending-drilldown",
                        query: {
                            let mut q = date_range_params(false);
                            q.extend([
                                QueryParamDoc {
                                    name: "group_key",
                                    param_type: "string",
                                    required: true,
                                    description: "Category group key from dashboard/breakdown.",
                                },
                                QueryParamDoc {
                                    name: "group_by_parent",
                                    param_type: "boolean",
                                    required: false,
                                    description: "Match parent category groups.",
                                },
                                QueryParamDoc {
                                    name: "page",
                                    param_type: "integer",
                                    required: false,
                                    description: "Page number (default 1).",
                                },
                                QueryParamDoc {
                                    name: "per_page",
                                    param_type: "integer",
                                    required: false,
                                    description: "Page size (default 50).",
                                },
                            ]);
                            q
                        },
                        body: None,
                        response: "Paginated transaction rows for one spending group.",
                        purpose: "Line-item detail behind a category slice.",
                        ai_use: "Explain specific purchases after identifying a category spike.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/income-drilldown",
                        query: {
                            let mut q = date_range_params(false);
                            q.extend([
                                QueryParamDoc {
                                    name: "group_key",
                                    param_type: "string",
                                    required: true,
                                    description: "Income category group key.",
                                },
                                QueryParamDoc {
                                    name: "group_by_parent",
                                    param_type: "boolean",
                                    required: false,
                                    description: "Match parent category groups.",
                                },
                                QueryParamDoc {
                                    name: "page",
                                    param_type: "integer",
                                    required: false,
                                    description: "Page number (default 1).",
                                },
                                QueryParamDoc {
                                    name: "per_page",
                                    param_type: "integer",
                                    required: false,
                                    description: "Page size (default 50).",
                                },
                            ]);
                            q
                        },
                        body: None,
                        response: "Paginated credit transactions for one income group.",
                        purpose: "Line-item detail behind an income category.",
                        ai_use: "Trace salary deposits or other income sources.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/spending-drilldown-by-name",
                        query: {
                            let mut q = date_range_params(false);
                            q.push(QueryParamDoc {
                                name: "group_key",
                                param_type: "string",
                                required: true,
                                description: "Merchant/description group key.",
                            });
                            q
                        },
                        body: None,
                        response: "Rows aggregated by normalized merchant name.",
                        purpose: "Merchant-level spending without full transaction list.",
                        ai_use: "Compare spend across vendors (e.g. supermarkets, utilities).",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/analytics/income-drilldown-by-name",
                        query: {
                            let mut q = date_range_params(false);
                            q.push(QueryParamDoc {
                                name: "group_key",
                                param_type: "string",
                                required: true,
                                description: "Payer/description group key.",
                            });
                            q
                        },
                        body: None,
                        response: "Rows aggregated by normalized payer name.",
                        purpose: "Payer-level income aggregation.",
                        ai_use: "Identify who paid you and how consistently.",
                        read_only: true,
                    },
                ],
            },
            EndpointGroup {
                id: "transactions",
                label: "Transactions",
                description: "Raw ledger lines, categorisation, and ML suggestions.",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/transactions",
                        query: vec![
                            QueryParamDoc {
                                name: "page",
                                param_type: "integer",
                                required: false,
                                description: "Page number.",
                            },
                            QueryParamDoc {
                                name: "per_page",
                                param_type: "integer",
                                required: false,
                                description: "Page size.",
                            },
                            QueryParamDoc {
                                name: "search",
                                param_type: "string",
                                required: false,
                                description: "Filter by description text.",
                            },
                            QueryParamDoc {
                                name: "uncategorized_only",
                                param_type: "boolean",
                                required: false,
                                description: "Only rows without a category.",
                            },
                            QueryParamDoc {
                                name: "include_suggestions",
                                param_type: "boolean",
                                required: false,
                                description: "Attach suggested category per row.",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Limit to one account.",
                            },
                        ],
                        body: None,
                        response: "Paginated transactions with optional account and transfer pair status.",
                        purpose: "Search and inspect individual ledger lines.",
                        ai_use: "Free-text search, audit uncategorized items, verify a specific payment.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "PATCH",
                        path: "/api/transactions/{id}/category",
                        query: vec![],
                        body: Some("{ category_id: number | null }"),
                        response: "Updated transaction.",
                        purpose: "Set category on one transaction.",
                        ai_use: "Apply corrections after analysis (requires user approval).",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PATCH",
                        path: "/api/transactions/categories",
                        query: vec![],
                        body: Some("{ transaction_ids: number[], category_id: number | null }"),
                        response: "{ updated: number }.",
                        purpose: "Bulk recategorise by transaction id.",
                        ai_use: "Batch-fix categories suggested by analysis.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PATCH",
                        path: "/api/transactions/categories-by-group",
                        query: vec![],
                        body: Some("{ group_key, category_id, start?, end?, account_id? }"),
                        response: "{ updated: number }.",
                        purpose: "Recategorise all transactions in a breakdown merchant group.",
                        ai_use: "Fix a whole merchant at once after drilldown.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/transactions/accept-suggestions",
                        query: vec![],
                        body: Some("{ transaction_ids: number[] }"),
                        response: "{ updated: number }.",
                        purpose: "Apply ML category suggestions for given ids.",
                        ai_use: "Accept high-confidence suggestions in bulk.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/transactions/recategorize-uncategorized",
                        query: vec![],
                        body: None,
                        response: "{ updated: number }.",
                        purpose: "Run auto-categoriser on all uncategorized rows.",
                        ai_use: "Housekeeping after importing new statements.",
                        read_only: false,
                    },
                ],
            },
            EndpointGroup {
                id: "accounts-transfers",
                label: "Accounts & transfers",
                description: "Bank accounts and inter-account transfer pairing.",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/accounts",
                        query: vec![QueryParamDoc {
                            name: "with_stats",
                            param_type: "boolean",
                            required: false,
                            description: "Include lastKnownBalance and lastKnownBalanceDate.",
                        }],
                        body: None,
                        response: "Financial accounts (with optional balance stats).",
                        purpose: "List linked bank accounts and parsers.",
                        ai_use: "Map account_id to human names; check latest balances.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/accounts",
                        query: vec![],
                        body: Some("{ bank_name, display_name, account_number, parser_name, account_type? }"),
                        response: "Created account.",
                        purpose: "Register a new account for statements.",
                        ai_use: "Rare; usually user-driven setup.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/accounts/{id}",
                        query: vec![],
                        body: Some("{ bank_name?, display_name?, account_type? }"),
                        response: "Updated account.",
                        purpose: "Rename or retype an account.",
                        ai_use: "Metadata fixes only.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/accounts/{id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Soft-delete an account.",
                        ai_use: "Destructive; avoid without explicit user request.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/transfers",
                        query: vec![],
                        body: None,
                        response: "Confirmed transfer pairs.",
                        purpose: "See which transactions are treated as internal moves.",
                        ai_use: "Explain why spend/income totals exclude certain OSKO lines.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/transfers/suggestions",
                        query: vec![QueryParamDoc {
                            name: "account_id",
                            param_type: "integer",
                            required: false,
                            description: "Limit suggestions involving this account.",
                        }],
                        body: None,
                        response: "Suggested transfer pairs (not yet excluded from analytics).",
                        purpose: "Detect likely inter-account transfers.",
                        ai_use: "Recommend user confirm pairs to fix double-counting.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/transfers",
                        query: vec![],
                        body: Some("{ out_transaction_id, in_transaction_id }"),
                        response: "Confirmed pair.",
                        purpose: "Mark two transactions as an internal transfer.",
                        ai_use: "Apply after user confirms a suggestion.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/transfers/dismiss",
                        query: vec![],
                        body: Some("{ out_transaction_id, in_transaction_id }"),
                        response: "Dismissed suggestion.",
                        purpose: "Hide a bad transfer suggestion.",
                        ai_use: "User says pair is not a transfer.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/transfers/{id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Undo a confirmed transfer pair.",
                        ai_use: "Revert mistaken confirmation.",
                        read_only: false,
                    },
                ],
            },
            EndpointGroup {
                id: "categories",
                label: "Categories & mappings",
                description: "Spending taxonomy and description-to-category rules.",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/categories",
                        query: vec![],
                        body: None,
                        response: "Category tree (active).",
                        purpose: "Labels and colours for categorisation.",
                        ai_use: "Resolve category_id to names in narratives.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/categories/{id}",
                        query: vec![],
                        body: None,
                        response: "Single category.",
                        purpose: "Category detail.",
                        ai_use: "Lookup one category.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/categories",
                        query: vec![],
                        body: Some("{ name, parent_id?, colour?, icon? }"),
                        response: "Created category.",
                        purpose: "Add a category.",
                        ai_use: "User-approved taxonomy changes only.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/categories/{id}",
                        query: vec![],
                        body: Some("{ name?, parent_id?, colour?, icon? }"),
                        response: "Updated category.",
                        purpose: "Edit category metadata.",
                        ai_use: "User-approved taxonomy changes only.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/categories/{id}",
                        query: vec![],
                        body: None,
                        response: "Soft-deleted category.",
                        purpose: "Retire a category.",
                        ai_use: "Destructive taxonomy change.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/categories/{id}/undelete",
                        query: vec![],
                        body: None,
                        response: "Restored category.",
                        purpose: "Restore soft-deleted category.",
                        ai_use: "Undo delete.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/categories/{id}/merge",
                        query: vec![],
                        body: Some("{ target_category_id }"),
                        response: "Merge result.",
                        purpose: "Merge duplicate categories.",
                        ai_use: "Consolidate after analysis finds duplicates.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PATCH",
                        path: "/api/categories/reorder",
                        query: vec![],
                        body: Some("{ ordered_ids: number[] }"),
                        response: "Reorder confirmation.",
                        purpose: "Change display order.",
                        ai_use: "UI preference; not analysis.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/category_mappings",
                        query: vec![],
                        body: None,
                        response: "Description pattern to category rules.",
                        purpose: "Auto-categorisation rules.",
                        ai_use: "Explain why certain merchants always map to a category.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/category_mappings",
                        query: vec![],
                        body: Some("{ pattern, category_id, ... }"),
                        response: "Created mapping.",
                        purpose: "Add auto-categorise rule.",
                        ai_use: "Persist a rule discovered during analysis.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/category_mappings/{id}",
                        query: vec![],
                        body: None,
                        response: "Mappings for a category id.",
                        purpose: "Rules targeting one category.",
                        ai_use: "Audit rules for a category.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/category_mappings/{id}",
                        query: vec![],
                        body: Some("Full mapping fields."),
                        response: "Updated mapping.",
                        purpose: "Edit a rule by mapping id.",
                        ai_use: "Fix pattern after false positives.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/category_mappings/{id}",
                        query: vec![],
                        body: None,
                        response: "Deleted mapping.",
                        purpose: "Remove a rule.",
                        ai_use: "Remove bad auto-categorisation.",
                        read_only: false,
                    },
                ],
            },
            EndpointGroup {
                id: "income-lender",
                label: "Income & lender expenses",
                description: "Salary streams and mortgage-style living expense buckets.",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/income-streams",
                        query: vec![
                            QueryParamDoc {
                                name: "min_occurrences",
                                param_type: "integer",
                                required: false,
                                description: "Detection threshold (default 3).",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Limit to one account.",
                            },
                        ],
                        body: None,
                        response: "Detected streams with frequency, amounts, and user profile fields.",
                        purpose: "Regular income sources (salary, etc.).",
                        ai_use: "Answer take-home vs gross, primary income, irregular pay.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/income-streams/profiles",
                        query: vec![],
                        body: Some("{ stream_key, display_label?, is_primary?, is_confirmed?, gross_monthly_dollars?, merged_into_key? }"),
                        response: "Saved profile.",
                        purpose: "Label or confirm an income stream.",
                        ai_use: "Persist user corrections to detected salary.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/lender-expenses/buckets",
                        query: vec![],
                        body: None,
                        response: "Canonical lender living-expense buckets.",
                        purpose: "Bucket definitions for loan applications.",
                        ai_use: "Map spending to lender categories.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/lender-expenses/mappings",
                        query: vec![],
                        body: None,
                        response: "Category to lender bucket assignments.",
                        purpose: "How app categories roll up to lender buckets.",
                        ai_use: "Explain bucket totals vs internal categories.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/lender-expenses/mappings",
                        query: vec![],
                        body: Some("{ category_id, bucket_key? } — null bucket_key excludes category."),
                        response: "{ ok: true }.",
                        purpose: "Override category bucket mapping.",
                        ai_use: "User mapping fixes.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/lender-expenses/summary",
                        query: vec![
                            QueryParamDoc {
                                name: "start_date",
                                param_type: "date",
                                required: true,
                                description: "Range start.",
                            },
                            QueryParamDoc {
                                name: "end_date",
                                param_type: "date",
                                required: true,
                                description: "Range end.",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Limit to one account.",
                            },
                        ],
                        body: None,
                        response: "Bucket totals, monthly averages, transaction counts.",
                        purpose: "Living expenses in lender-friendly groupings.",
                        ai_use: "Affordability and HEM-style analysis.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/lender-expenses/buckets/{bucket_key}/breakdown",
                        query: vec![
                            QueryParamDoc {
                                name: "start_date",
                                param_type: "date",
                                required: true,
                                description: "Range start.",
                            },
                            QueryParamDoc {
                                name: "end_date",
                                param_type: "date",
                                required: true,
                                description: "Range end.",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Limit to one account.",
                            },
                        ],
                        body: None,
                        response: "Category-level lines inside one lender bucket.",
                        purpose: "Drill into a single lender bucket.",
                        ai_use: "Explain what drove 'groceries' or 'utilities' bucket totals.",
                        read_only: true,
                    },
                ],
            },
            EndpointGroup {
                id: "predictions",
                label: "Predictions & planning",
                description: "Forward balance projections, scenarios, goals, and planned spending.",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/predictions/baseline",
                        query: vec![
                            QueryParamDoc {
                                name: "from",
                                param_type: "date",
                                required: true,
                                description: "Projection start.",
                            },
                            QueryParamDoc {
                                name: "to",
                                param_type: "date",
                                required: true,
                                description: "Projection end.",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Single-account projection.",
                            },
                        ],
                        body: None,
                        response: "Monthly baseline balance points.",
                        purpose: "Project balance from history and planned spending.",
                        ai_use: "Answer 'where will I be in N months'.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/predictions/baseline",
                        query: vec![
                            QueryParamDoc {
                                name: "from",
                                param_type: "date",
                                required: true,
                                description: "Projection start.",
                            },
                            QueryParamDoc {
                                name: "to",
                                param_type: "date",
                                required: true,
                                description: "Projection end.",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Single-account projection.",
                            },
                        ],
                        body: Some("{ repeat_adjustments?: [{ amount_cents, frequency, start_date, end_date? }] }"),
                        response: "Baseline with optional repeat adjustments applied.",
                        purpose: "What-if baseline with extra recurring items.",
                        ai_use: "Model new recurring cost or income in projection.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/predictions/scenario/{id}",
                        query: vec![
                            QueryParamDoc {
                                name: "from",
                                param_type: "date",
                                required: true,
                                description: "Projection start.",
                            },
                            QueryParamDoc {
                                name: "to",
                                param_type: "date",
                                required: true,
                                description: "Projection end.",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Single-account projection.",
                            },
                        ],
                        body: None,
                        response: "Monthly points for saved scenario.",
                        purpose: "Compare a named what-if scenario.",
                        ai_use: "Contrast baseline vs user-defined scenario.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/predictions/scenario/{id}",
                        query: vec![
                            QueryParamDoc {
                                name: "from",
                                param_type: "date",
                                required: true,
                                description: "Projection start.",
                            },
                            QueryParamDoc {
                                name: "to",
                                param_type: "date",
                                required: true,
                                description: "Projection end.",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Single-account projection.",
                            },
                        ],
                        body: Some("{ repeat_adjustments?: [...] } — same shape as baseline POST."),
                        response: "Scenario projection with ad-hoc adjustments.",
                        purpose: "Temporary tweaks on top of a saved scenario.",
                        ai_use: "One-off what-if without saving scenario.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/prediction-scenarios",
                        query: vec![],
                        body: None,
                        response: "Saved scenarios with adjustment lines.",
                        purpose: "List user what-if scenarios.",
                        ai_use: "Pick scenario id for projection compare.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/prediction-scenarios",
                        query: vec![],
                        body: Some("{ name, lines: [{ name, amount_cents, frequency, start_date, end_date?, category_id? }] }"),
                        response: "Created scenario.",
                        purpose: "Save a new what-if.",
                        ai_use: "Persist analysis recommendation as scenario.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/prediction-scenarios/{id}",
                        query: vec![],
                        body: Some("{ name?, lines? }"),
                        response: "Updated scenario.",
                        purpose: "Edit scenario.",
                        ai_use: "Update saved what-if.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/prediction-scenarios/{id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Soft-delete scenario.",
                        ai_use: "Cleanup.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/prediction-goals",
                        query: vec![],
                        body: None,
                        response: "Savings goals with target amount and date.",
                        purpose: "List financial goals.",
                        ai_use: "Check progress toward targets using projections.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/prediction-goals",
                        query: vec![],
                        body: Some("{ name, target_amount_cents, target_date }"),
                        response: "Created goal.",
                        purpose: "Add savings goal.",
                        ai_use: "User-defined target from planning session.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/prediction-goals/{id}",
                        query: vec![],
                        body: Some("{ name?, target_amount_cents?, target_date? }"),
                        response: "Updated goal.",
                        purpose: "Edit goal.",
                        ai_use: "Adjust target after analysis.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/prediction-goals/{id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Soft-delete goal.",
                        ai_use: "Cleanup.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/planned-spending",
                        query: vec![
                            QueryParamDoc {
                                name: "from",
                                param_type: "date",
                                required: false,
                                description: "Filter start.",
                            },
                            QueryParamDoc {
                                name: "to",
                                param_type: "date",
                                required: false,
                                description: "Filter end.",
                            },
                        ],
                        body: None,
                        response: "Future or recurring planned expenses.",
                        purpose: "Known upcoming costs feeding projections.",
                        ai_use: "Include holidays, insurance renewals in forward view.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/planned-spending",
                        query: vec![],
                        body: Some("{ name, amount_cents, start_date, end_date?, category_id?, notes? }"),
                        response: "Created planned item.",
                        purpose: "Add planned expense.",
                        ai_use: "Record planned spend from conversation.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/planned-spending/{id}",
                        query: vec![],
                        body: Some("{ name?, amount_cents?, start_date?, end_date?, category_id?, notes? }"),
                        response: "Updated planned item.",
                        purpose: "Edit planned expense.",
                        ai_use: "Adjust plan.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/planned-spending/{id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Remove planned expense.",
                        ai_use: "Cleanup.",
                        read_only: false,
                    },
                ],
            },
            EndpointGroup {
                id: "balance-sheet",
                label: "Assets & liabilities",
                description: "Manual balance-sheet items outside bank transactions.",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/assets",
                        query: vec![],
                        body: None,
                        response: "Assets with latest valuations.",
                        purpose: "Property, investments, etc.",
                        ai_use: "Net worth context beyond cash accounts.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/assets",
                        query: vec![],
                        body: Some("{ name, asset_type?, notes? }"),
                        response: "Created asset.",
                        purpose: "Add manual asset.",
                        ai_use: "User data entry.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/assets/{id}",
                        query: vec![],
                        body: Some("{ name?, asset_type?, notes? }"),
                        response: "Updated asset.",
                        purpose: "Edit asset metadata.",
                        ai_use: "Metadata fixes.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/assets/{id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Soft-delete asset.",
                        ai_use: "Destructive.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/assets/{id}/valuations",
                        query: vec![],
                        body: None,
                        response: "Valuation history for one asset.",
                        purpose: "Track asset value over time.",
                        ai_use: "Explain net worth changes from property/shares.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/assets/{id}/valuations",
                        query: vec![],
                        body: Some("{ valued_on, amount_cents, notes? }"),
                        response: "Created valuation.",
                        purpose: "Record new asset value.",
                        ai_use: "Update valuation after analysis period.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/assets/{id}/valuations/{valuation_id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Remove valuation point.",
                        ai_use: "Correct mistaken entry.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/liabilities",
                        query: vec![],
                        body: None,
                        response: "Liabilities with latest balances.",
                        purpose: "Loans, mortgages, etc.",
                        ai_use: "Debt side of net worth.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/liabilities",
                        query: vec![],
                        body: Some("{ name, liability_type?, notes? }"),
                        response: "Created liability.",
                        purpose: "Add manual liability.",
                        ai_use: "User data entry.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "PUT",
                        path: "/api/liabilities/{id}",
                        query: vec![],
                        body: Some("{ name?, liability_type?, notes? }"),
                        response: "Updated liability.",
                        purpose: "Edit liability metadata.",
                        ai_use: "Metadata fixes.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/liabilities/{id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Soft-delete liability.",
                        ai_use: "Destructive.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/liabilities/{id}/balances",
                        query: vec![],
                        body: None,
                        response: "Balance history for one liability.",
                        purpose: "Track debt balance over time.",
                        ai_use: "Paydown progress.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/liabilities/{id}/balances",
                        query: vec![],
                        body: Some("{ as_of, amount_cents, notes? }"),
                        response: "Created balance snapshot.",
                        purpose: "Record liability balance.",
                        ai_use: "Update debt figure.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/liabilities/{id}/balances/{balance_id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Remove balance snapshot.",
                        ai_use: "Correct mistaken entry.",
                        read_only: false,
                    },
                ],
            },
            EndpointGroup {
                id: "statements",
                label: "Statements",
                description: "PDF import and statement coverage (usually user-driven, not analysis).",
                endpoints: vec![
                    EndpointDoc {
                        method: "GET",
                        path: "/api/statements",
                        query: vec![
                            QueryParamDoc {
                                name: "page",
                                param_type: "integer",
                                required: false,
                                description: "Page number (default 1).",
                            },
                            QueryParamDoc {
                                name: "per_page",
                                param_type: "integer",
                                required: false,
                                description: "Page size (default 50).",
                            },
                            QueryParamDoc {
                                name: "account_id",
                                param_type: "integer",
                                required: false,
                                description: "Filter by account.",
                            },
                        ],
                        body: None,
                        response: "Paginated imported statements with period ranges.",
                        purpose: "See which PDFs are loaded and their date coverage.",
                        ai_use: "Detect data gaps before drawing conclusions.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "GET",
                        path: "/api/statements/missing-periods",
                        query: vec![QueryParamDoc {
                            name: "account_id",
                            param_type: "integer",
                            required: false,
                            description: "Check one account or all.",
                        }],
                        body: None,
                        response: "Months with no statement coverage.",
                        purpose: "Find gaps in imported data.",
                        ai_use: "Warn user that analysis may be incomplete.",
                        read_only: true,
                    },
                    EndpointDoc {
                        method: "POST",
                        path: "/api/statements",
                        query: vec![
                            QueryParamDoc {
                                name: "preview",
                                param_type: "boolean",
                                required: false,
                                description: "Parse only; do not persist (default false).",
                            },
                            QueryParamDoc {
                                name: "replace",
                                param_type: "boolean",
                                required: false,
                                description: "Replace conflicting statement on import.",
                            },
                            QueryParamDoc {
                                name: "parser",
                                param_type: "string",
                                required: false,
                                description: "Force parser name.",
                            },
                        ],
                        body: Some("multipart/form-data with PDF file(s)."),
                        response: "Import result or preview of conflicts.",
                        purpose: "Upload bank statement PDFs.",
                        ai_use: "Not typical for read-only analysis agents.",
                        read_only: false,
                    },
                    EndpointDoc {
                        method: "DELETE",
                        path: "/api/statements/{id}",
                        query: vec![],
                        body: None,
                        response: "204 No Content.",
                        purpose: "Soft-delete a statement and its transactions.",
                        ai_use: "Destructive; avoid without explicit user request.",
                        read_only: false,
                    },
                ],
            },
        ],
    }
}

pub async fn get_api_catalog() -> impl Responder {
    HttpResponse::Ok().json(catalog())
}
