use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};

use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "funds-release", about = "Build and publish Funds Manager releases")]
struct Cli {
	#[command(subcommand)]
	command: Commands,
}

#[derive(Subcommand)]
enum Commands {
	/// Build frontend + release binary and package a tarball in dist/
	Bundle {
		#[arg(long, default_value = "dist")]
		output_dir: PathBuf,
		#[arg(long)]
		skip_frontend: bool,
	},
	/// Bundle and create or update a GitHub Release (requires gh CLI)
	Publish {
		#[arg(long, default_value = "dist")]
		output_dir: PathBuf,
		#[arg(long)]
		skip_frontend: bool,
		#[arg(long, help = "Create a draft release")]
		draft: bool,
		#[arg(long, help = "Release notes file (default: auto-generated by gh)")]
		notes_file: Option<PathBuf>,
	},
}

fn main() -> ExitCode {
	let cli = Cli::parse();
	let root = workspace_root();

	match cli.command {
		Commands::Bundle {
			output_dir,
			skip_frontend,
		} => match bundle(&root, &output_dir, skip_frontend) {
			Ok(artifact) => {
				println!("{}", artifact.display());
				ExitCode::SUCCESS
			}
			Err(error) => {
				eprintln!("{error}");
				ExitCode::FAILURE
			}
		},
		Commands::Publish {
			output_dir,
			skip_frontend,
			draft,
			notes_file,
		} => match publish(&root, &output_dir, skip_frontend, draft, notes_file.as_deref()) {
			Ok(()) => ExitCode::SUCCESS,
			Err(error) => {
				eprintln!("{error}");
				ExitCode::FAILURE
			}
		},
	}
}

fn workspace_root() -> PathBuf {
	let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
	manifest
		.parent()
		.and_then(|p| p.parent())
		.expect("funds-release crate should live at crates/funds-release")
		.to_path_buf()
}

fn app_version(root: &Path) -> Result<String, String> {
	let content = fs::read_to_string(root.join("app/Cargo.toml"))
		.map_err(|error| format!("read app/Cargo.toml: {error}"))?;
	for line in content.lines() {
		if let Some(rest) = line.strip_prefix("version = \"") {
			let version = rest.trim_end_matches('"');
			if version.is_empty() {
				break;
			}
			return Ok(version.to_string());
		}
	}
	Err("version not found in app/Cargo.toml".to_string())
}

fn platform_slug() -> String {
	format!("{}-{}", std::env::consts::OS, std::env::consts::ARCH)
}

fn run_step(label: &str, mut command: Command) -> Result<(), String> {
	println!("→ {label}");
	let status = command
		.status()
		.map_err(|error| format!("{label}: {error}"))?;
	if status.success() {
		Ok(())
	} else {
		Err(format!("{label} failed (exit {status})"))
	}
}

fn build_frontend(root: &Path) -> Result<(), String> {
	let frontend = root.join("frontend");
	let mut pnpm_install = Command::new("pnpm");
	pnpm_install
		.args(["install", "--frozen-lockfile"])
		.current_dir(&frontend)
		.stdin(Stdio::inherit())
		.stdout(Stdio::inherit())
		.stderr(Stdio::inherit());
	run_step("pnpm install", pnpm_install)?;

	let mut pnpm_build = Command::new("pnpm");
	pnpm_build
		.args(["run", "build:embed"])
		.current_dir(&frontend)
		.stdin(Stdio::inherit())
		.stdout(Stdio::inherit())
		.stderr(Stdio::inherit());
	run_step("pnpm run build:embed", pnpm_build)
}

fn build_server(root: &Path) -> Result<(), String> {
	let mut cargo_build = Command::new("cargo");
	cargo_build
		.args(["build", "--release", "-p", "server_v2"])
		.current_dir(root)
		.stdin(Stdio::inherit())
		.stdout(Stdio::inherit())
		.stderr(Stdio::inherit());
	run_step("cargo build --release -p server_v2", cargo_build)
}

fn bundle(
	root: &Path,
	output_dir: &Path,
	skip_frontend: bool,
) -> Result<PathBuf, String> {
	let version = app_version(root)?;
	let platform = platform_slug();
	let pkg_name = format!("funds-manager-{version}");
	let artifact_name = format!("{pkg_name}-{platform}.tar.gz");
	let pkg_dir = output_dir.join(&pkg_name);
	let artifact = output_dir.join(&artifact_name);

	if !skip_frontend {
		build_frontend(root)?;
	} else {
		println!("→ skipping frontend build");
	}

	build_server(root)?;

	let binary = root.join("target/release/server_v2");
	if !binary.is_file() {
		return Err(format!("missing release binary: {}", binary.display()));
	}

	let pdfium = root.join("app/lib/libpdfium.so");
	if !pdfium.is_file() {
		return Err(format!("missing PDFium library: {}", pdfium.display()));
	}

	if pkg_dir.exists() {
		fs::remove_dir_all(&pkg_dir)
			.map_err(|error| format!("clean {}: {error}", pkg_dir.display()))?;
	}
	fs::create_dir_all(pkg_dir.join("lib"))
		.map_err(|error| format!("create package dir: {error}"))?;

	fs::copy(&binary, pkg_dir.join("server_v2"))
		.map_err(|error| format!("copy binary: {error}"))?;
	fs::copy(&pdfium, pkg_dir.join("lib/libpdfium.so"))
		.map_err(|error| format!("copy pdfium: {error}"))?;

	let readme = format!(
		"Funds Manager {version} ({platform})\n\n\
1. Set DATABASE_URL\n\
2. Run ./server_v2\n\
3. Open http://127.0.0.1:2020\n\n\
PDFium: lib/libpdfium.so (set PDFIUM_LIBRARY_PATH=./lib/libpdfium.so if needed)\n"
	);
	fs::write(pkg_dir.join("README.txt"), readme)
		.map_err(|error| format!("write README.txt: {error}"))?;

	if artifact.exists() {
		fs::remove_file(&artifact)
			.map_err(|error| format!("remove old artifact: {error}"))?;
	}
	fs::create_dir_all(output_dir).map_err(|error| format!("create output dir: {error}"))?;

	let mut tar_cmd = Command::new("tar");
	tar_cmd
		.args(["-czf", artifact.to_str().expect("utf-8 path"), "-C"])
		.arg(output_dir)
		.arg(&pkg_name)
		.current_dir(root)
		.stdin(Stdio::inherit())
		.stdout(Stdio::inherit())
		.stderr(Stdio::inherit());
	run_step(&format!("tar {}", artifact_name), tar_cmd)?;

	Ok(artifact)
}

fn gh_available() -> Result<(), String> {
	let output = Command::new("gh")
		.arg("auth")
		.arg("status")
		.output()
		.map_err(|error| format!("gh not found ({error}); install https://cli.github.com"))?;
	if output.status.success() {
		Ok(())
	} else {
		Err("gh auth required: run `gh auth login`".to_string())
	}
}

fn publish(
	root: &Path,
	output_dir: &Path,
	skip_frontend: bool,
	draft: bool,
	notes_file: Option<&Path>,
) -> Result<(), String> {
	gh_available()?;
	let version = app_version(root)?;
	let tag = format!("v{version}");
	let artifact = bundle(root, output_dir, skip_frontend)?;

	let release_exists = Command::new("gh")
		.args(["release", "view", &tag])
		.stdout(Stdio::null())
		.stderr(Stdio::null())
		.status()
		.map_err(|error| format!("gh release view: {error}"))?
		.success();

	if release_exists {
		println!("→ upload to existing release {tag}");
		let mut upload = Command::new("gh");
		upload.args(["release", "upload", &tag, artifact.to_str().expect("utf-8 path")]);
		return run_step("gh release upload", upload);
	}

	println!("→ create release {tag}");
	let mut create = Command::new("gh");
	create.arg("release").arg("create").arg(&tag);
	create.arg(artifact.to_str().expect("utf-8 path"));
	if draft {
		create.arg("--draft");
	}
	if let Some(notes) = notes_file {
		create.args(["--notes-file", notes.to_str().expect("utf-8 path")]);
	} else {
		create.arg("--generate-notes");
	}
	create.args(["--title", &tag]);

	run_step("gh release create", create)
}
